/*
 * WireMock
 *
 * WireMock offers a REST API for administration, troubleshooting and analysis purposes
 *
 * The version of the OpenAPI document: 3.13.2
 * 
 * Generated by: https://openapi-generator.tech
 */


use reqwest;
use serde::{Deserialize, Serialize, de::Error as _};
use crate::{apis::ResponseContent, models};
use super::{Error, configuration, ContentType};


/// struct for typed errors of method [`count_requests_by_criteria`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum CountRequestsByCriteriaError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`delete_all_requests_in_journal`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum DeleteAllRequestsInJournalError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`delete_request_by_id`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum DeleteRequestByIdError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`empty_request_journal`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum EmptyRequestJournalError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`find_requests_by_criteria`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum FindRequestsByCriteriaError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`find_unmatched_requests`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum FindUnmatchedRequestsError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`get_all_requests_in_journal`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetAllRequestsInJournalError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`get_request_by_id`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetRequestByIdError {
    Status404(),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`remove_requests_by_criteria`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum RemoveRequestsByCriteriaError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`remove_requests_by_metadata`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum RemoveRequestsByMetadataError {
    UnknownValue(serde_json::Value),
}


/// Count requests logged in the journal matching the specified criteria
pub async fn count_requests_by_criteria(configuration: &configuration::Configuration, request_pattern: models::RequestPattern) -> Result<models::CountRequestsByCriteria200Response, Error<CountRequestsByCriteriaError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_body_request_pattern = request_pattern;

    let uri_str = format!("{}/__admin/requests/count", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::POST, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    req_builder = req_builder.json(&p_body_request_pattern);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::CountRequestsByCriteria200Response`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::CountRequestsByCriteria200Response`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<CountRequestsByCriteriaError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

pub async fn delete_all_requests_in_journal(configuration: &configuration::Configuration, ) -> Result<(), Error<DeleteAllRequestsInJournalError>> {

    let uri_str = format!("{}/__admin/requests", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::DELETE, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();

    if !status.is_client_error() && !status.is_server_error() {
        Ok(())
    } else {
        let content = resp.text().await?;
        let entity: Option<DeleteAllRequestsInJournalError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

pub async fn delete_request_by_id(configuration: &configuration::Configuration, request_id: &str) -> Result<(), Error<DeleteRequestByIdError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_request_id = request_id;

    let uri_str = format!("{}/__admin/requests/{requestId}", configuration.base_path, requestId=crate::apis::urlencode(p_path_request_id));
    let mut req_builder = configuration.client.request(reqwest::Method::DELETE, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();

    if !status.is_client_error() && !status.is_server_error() {
        Ok(())
    } else {
        let content = resp.text().await?;
        let entity: Option<DeleteRequestByIdError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

#[deprecated]
pub async fn empty_request_journal(configuration: &configuration::Configuration, ) -> Result<(), Error<EmptyRequestJournalError>> {

    let uri_str = format!("{}/__admin/requests/reset", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::POST, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();

    if !status.is_client_error() && !status.is_server_error() {
        Ok(())
    } else {
        let content = resp.text().await?;
        let entity: Option<EmptyRequestJournalError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Retrieve details of requests logged in the journal matching the specified criteria
pub async fn find_requests_by_criteria(configuration: &configuration::Configuration, request_pattern: models::RequestPattern) -> Result<(), Error<FindRequestsByCriteriaError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_body_request_pattern = request_pattern;

    let uri_str = format!("{}/__admin/requests/find", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::POST, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    req_builder = req_builder.json(&p_body_request_pattern);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();

    if !status.is_client_error() && !status.is_server_error() {
        Ok(())
    } else {
        let content = resp.text().await?;
        let entity: Option<FindRequestsByCriteriaError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Get details of logged requests that weren't matched by any stub mapping
pub async fn find_unmatched_requests(configuration: &configuration::Configuration, ) -> Result<(), Error<FindUnmatchedRequestsError>> {

    let uri_str = format!("{}/__admin/requests/unmatched", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();

    if !status.is_client_error() && !status.is_server_error() {
        Ok(())
    } else {
        let content = resp.text().await?;
        let entity: Option<FindUnmatchedRequestsError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

pub async fn get_all_requests_in_journal(configuration: &configuration::Configuration, limit: Option<&str>, since: Option<&str>) -> Result<(), Error<GetAllRequestsInJournalError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_query_limit = limit;
    let p_query_since = since;

    let uri_str = format!("{}/__admin/requests", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref param_value) = p_query_limit {
        req_builder = req_builder.query(&[("limit", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_since {
        req_builder = req_builder.query(&[("since", &param_value.to_string())]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();

    if !status.is_client_error() && !status.is_server_error() {
        Ok(())
    } else {
        let content = resp.text().await?;
        let entity: Option<GetAllRequestsInJournalError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

pub async fn get_request_by_id(configuration: &configuration::Configuration, request_id: &str) -> Result<(), Error<GetRequestByIdError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_request_id = request_id;

    let uri_str = format!("{}/__admin/requests/{requestId}", configuration.base_path, requestId=crate::apis::urlencode(p_path_request_id));
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();

    if !status.is_client_error() && !status.is_server_error() {
        Ok(())
    } else {
        let content = resp.text().await?;
        let entity: Option<GetRequestByIdError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Removed requests logged in the journal matching the specified criteria
pub async fn remove_requests_by_criteria(configuration: &configuration::Configuration, request_pattern: models::RequestPattern) -> Result<(), Error<RemoveRequestsByCriteriaError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_body_request_pattern = request_pattern;

    let uri_str = format!("{}/__admin/requests/remove", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::POST, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    req_builder = req_builder.json(&p_body_request_pattern);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();

    if !status.is_client_error() && !status.is_server_error() {
        Ok(())
    } else {
        let content = resp.text().await?;
        let entity: Option<RemoveRequestsByCriteriaError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

pub async fn remove_requests_by_metadata(configuration: &configuration::Configuration, content_pattern: Option<models::ContentPattern>) -> Result<(), Error<RemoveRequestsByMetadataError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_body_content_pattern = content_pattern;

    let uri_str = format!("{}/__admin/requests/remove-by-metadata", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::POST, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    req_builder = req_builder.json(&p_body_content_pattern);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();

    if !status.is_client_error() && !status.is_server_error() {
        Ok(())
    } else {
        let content = resp.text().await?;
        let entity: Option<RemoveRequestsByMetadataError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

