/*
 * WireMock
 *
 * WireMock offers a REST API for administration, troubleshooting and analysis purposes
 *
 * The version of the OpenAPI document: 3.13.2
 * 
 * Generated by: https://openapi-generator.tech
 */


use reqwest;
use serde::{Deserialize, Serialize, de::Error as _};
use crate::{apis::ResponseContent, models};
use super::{Error, configuration, ContentType};


/// struct for typed errors of method [`create_new_stub_mapping`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum CreateNewStubMappingError {
    Status422(models::BadRequestEntity),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`delete_all_stub_mappings`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum DeleteAllStubMappingsError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`delete_stub_mapping`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum DeleteStubMappingError {
    Status404(),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`find_stub_mappings_by_metadata`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum FindStubMappingsByMetadataError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`find_unmatched_stub_mappings`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum FindUnmatchedStubMappingsError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`get_all_stub_mappings`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetAllStubMappingsError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`get_stub_mapping_by_id`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetStubMappingByIdError {
    Status404(),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`import_stub_mappings`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ImportStubMappingsError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`persist_stub_mappings`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum PersistStubMappingsError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`remove_stub_mappings_by_metadata`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum RemoveStubMappingsByMetadataError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`remove_unmatched_stub_mappings`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum RemoveUnmatchedStubMappingsError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`reset_stub_mappings`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ResetStubMappingsError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`update_stub_mapping`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum UpdateStubMappingError {
    Status404(),
    UnknownValue(serde_json::Value),
}


pub async fn create_new_stub_mapping(configuration: &configuration::Configuration, stub_mapping: Option<models::StubMapping>) -> Result<models::StubMapping, Error<CreateNewStubMappingError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_body_stub_mapping = stub_mapping;

    let uri_str = format!("{}/__admin/mappings", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::POST, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    req_builder = req_builder.json(&p_body_stub_mapping);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::StubMapping`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::StubMapping`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<CreateNewStubMappingError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

pub async fn delete_all_stub_mappings(configuration: &configuration::Configuration, ) -> Result<(), Error<DeleteAllStubMappingsError>> {

    let uri_str = format!("{}/__admin/mappings", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::DELETE, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();

    if !status.is_client_error() && !status.is_server_error() {
        Ok(())
    } else {
        let content = resp.text().await?;
        let entity: Option<DeleteAllStubMappingsError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

pub async fn delete_stub_mapping(configuration: &configuration::Configuration, stub_mapping_id: &str) -> Result<(), Error<DeleteStubMappingError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_stub_mapping_id = stub_mapping_id;

    let uri_str = format!("{}/__admin/mappings/{stubMappingId}", configuration.base_path, stubMappingId=crate::apis::urlencode(p_path_stub_mapping_id));
    let mut req_builder = configuration.client.request(reqwest::Method::DELETE, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();

    if !status.is_client_error() && !status.is_server_error() {
        Ok(())
    } else {
        let content = resp.text().await?;
        let entity: Option<DeleteStubMappingError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Find stubs by matching on their metadata
pub async fn find_stub_mappings_by_metadata(configuration: &configuration::Configuration, content_pattern: models::ContentPattern) -> Result<models::StubMappings, Error<FindStubMappingsByMetadataError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_body_content_pattern = content_pattern;

    let uri_str = format!("{}/__admin/mappings/find-by-metadata", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::POST, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    req_builder = req_builder.json(&p_body_content_pattern);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::StubMappings`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::StubMappings`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<FindStubMappingsByMetadataError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Find stub mappings that haven't matched any requests in the journal
pub async fn find_unmatched_stub_mappings(configuration: &configuration::Configuration, ) -> Result<models::StubMappings, Error<FindUnmatchedStubMappingsError>> {

    let uri_str = format!("{}/__admin/mappings/unmatched", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::StubMappings`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::StubMappings`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<FindUnmatchedStubMappingsError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

pub async fn get_all_stub_mappings(configuration: &configuration::Configuration, limit: Option<i32>, offset: Option<i32>) -> Result<models::StubMappings, Error<GetAllStubMappingsError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_query_limit = limit;
    let p_query_offset = offset;

    let uri_str = format!("{}/__admin/mappings", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref param_value) = p_query_limit {
        req_builder = req_builder.query(&[("limit", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_offset {
        req_builder = req_builder.query(&[("offset", &param_value.to_string())]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::StubMappings`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::StubMappings`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<GetAllStubMappingsError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

pub async fn get_stub_mapping_by_id(configuration: &configuration::Configuration, stub_mapping_id: &str) -> Result<models::StubMapping, Error<GetStubMappingByIdError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_stub_mapping_id = stub_mapping_id;

    let uri_str = format!("{}/__admin/mappings/{stubMappingId}", configuration.base_path, stubMappingId=crate::apis::urlencode(p_path_stub_mapping_id));
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::StubMapping`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::StubMapping`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<GetStubMappingByIdError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Import given stub mappings to the backing store
pub async fn import_stub_mappings(configuration: &configuration::Configuration, ) -> Result<(), Error<ImportStubMappingsError>> {

    let uri_str = format!("{}/__admin/mappings/import", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::POST, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();

    if !status.is_client_error() && !status.is_server_error() {
        Ok(())
    } else {
        let content = resp.text().await?;
        let entity: Option<ImportStubMappingsError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Save all persistent stub mappings to the backing store
pub async fn persist_stub_mappings(configuration: &configuration::Configuration, ) -> Result<(), Error<PersistStubMappingsError>> {

    let uri_str = format!("{}/__admin/mappings/save", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::POST, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();

    if !status.is_client_error() && !status.is_server_error() {
        Ok(())
    } else {
        let content = resp.text().await?;
        let entity: Option<PersistStubMappingsError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

pub async fn remove_stub_mappings_by_metadata(configuration: &configuration::Configuration, content_pattern: Option<models::ContentPattern>) -> Result<(), Error<RemoveStubMappingsByMetadataError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_body_content_pattern = content_pattern;

    let uri_str = format!("{}/__admin/mappings/remove-by-metadata", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::POST, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    req_builder = req_builder.json(&p_body_content_pattern);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();

    if !status.is_client_error() && !status.is_server_error() {
        Ok(())
    } else {
        let content = resp.text().await?;
        let entity: Option<RemoveStubMappingsByMetadataError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Remove stub mappings that haven't matched any requests in the journal
pub async fn remove_unmatched_stub_mappings(configuration: &configuration::Configuration, ) -> Result<(), Error<RemoveUnmatchedStubMappingsError>> {

    let uri_str = format!("{}/__admin/mappings/unmatched", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::DELETE, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();

    if !status.is_client_error() && !status.is_server_error() {
        Ok(())
    } else {
        let content = resp.text().await?;
        let entity: Option<RemoveUnmatchedStubMappingsError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Restores stub mappings to the defaults defined back in the backing store
pub async fn reset_stub_mappings(configuration: &configuration::Configuration, ) -> Result<(), Error<ResetStubMappingsError>> {

    let uri_str = format!("{}/__admin/mappings/reset", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::POST, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();

    if !status.is_client_error() && !status.is_server_error() {
        Ok(())
    } else {
        let content = resp.text().await?;
        let entity: Option<ResetStubMappingsError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

pub async fn update_stub_mapping(configuration: &configuration::Configuration, stub_mapping_id: &str, stub_mapping: Option<models::StubMapping>) -> Result<models::StubMapping, Error<UpdateStubMappingError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_stub_mapping_id = stub_mapping_id;
    let p_body_stub_mapping = stub_mapping;

    let uri_str = format!("{}/__admin/mappings/{stubMappingId}", configuration.base_path, stubMappingId=crate::apis::urlencode(p_path_stub_mapping_id));
    let mut req_builder = configuration.client.request(reqwest::Method::PUT, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    req_builder = req_builder.json(&p_body_stub_mapping);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::StubMapping`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::StubMapping`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<UpdateStubMappingError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

