/*
 * WireMock
 *
 * WireMock offers a REST API for administration, troubleshooting and analysis purposes
 *
 * The version of the OpenAPI document: 3.13.2
 * 
 * Generated by: https://openapi-generator.tech
 */


use reqwest;
use serde::{Deserialize, Serialize, de::Error as _};
use crate::{apis::ResponseContent, models};
use super::{Error, configuration, ContentType};


/// struct for typed errors of method [`find_near_misses_for_request`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum FindNearMissesForRequestError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`find_near_misses_for_request_pattern`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum FindNearMissesForRequestPatternError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`retrieve_near_misses_for_unmatched_requests`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum RetrieveNearMissesForUnmatchedRequestsError {
    UnknownValue(serde_json::Value),
}


/// Find at most 3 near misses for closest stub mappings to the specified request
pub async fn find_near_misses_for_request(configuration: &configuration::Configuration, logged_request: models::LoggedRequest) -> Result<models::RetrieveNearMissesForUnmatchedRequests200Response, Error<FindNearMissesForRequestError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_body_logged_request = logged_request;

    let uri_str = format!("{}/__admin/near-misses/request", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::POST, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    req_builder = req_builder.json(&p_body_logged_request);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::RetrieveNearMissesForUnmatchedRequests200Response`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::RetrieveNearMissesForUnmatchedRequests200Response`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<FindNearMissesForRequestError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Find at most 3 near misses for closest logged requests to the specified request pattern
pub async fn find_near_misses_for_request_pattern(configuration: &configuration::Configuration, request_pattern: models::RequestPattern) -> Result<models::RetrieveNearMissesForUnmatchedRequests200Response, Error<FindNearMissesForRequestPatternError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_body_request_pattern = request_pattern;

    let uri_str = format!("{}/__admin/near-misses/request-pattern", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::POST, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    req_builder = req_builder.json(&p_body_request_pattern);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::RetrieveNearMissesForUnmatchedRequests200Response`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::RetrieveNearMissesForUnmatchedRequests200Response`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<FindNearMissesForRequestPatternError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Retrieve near-misses for all unmatched requests
pub async fn retrieve_near_misses_for_unmatched_requests(configuration: &configuration::Configuration, ) -> Result<models::RetrieveNearMissesForUnmatchedRequests200Response, Error<RetrieveNearMissesForUnmatchedRequestsError>> {

    let uri_str = format!("{}/__admin/requests/unmatched/near-misses", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::RetrieveNearMissesForUnmatchedRequests200Response`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::RetrieveNearMissesForUnmatchedRequests200Response`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<RetrieveNearMissesForUnmatchedRequestsError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

