/*
 * WireMock
 *
 * WireMock offers a REST API for administration, troubleshooting and analysis purposes
 *
 * The version of the OpenAPI document: 3.13.2
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ContentPattern {
    EqualToPattern(Box<models::EqualToPattern>),
    BinaryEqualToPattern(Box<models::BinaryEqualToPattern>),
    ContainsPattern(Box<models::ContainsPattern>),
    DoesNotContainPattern(Box<models::DoesNotContainPattern>),
    MatchesPattern(Box<models::MatchesPattern>),
    DoesNotMatchPattern(Box<models::DoesNotMatchPattern>),
    NotPattern(Box<models::NotPattern>),
    BeforePattern(Box<models::BeforePattern>),
    AfterPattern(Box<models::AfterPattern>),
    EqualToDateTimePattern(Box<models::EqualToDateTimePattern>),
    EqualToJsonPattern(Box<models::EqualToJsonPattern>),
    MatchesJsonPathPattern(Box<models::MatchesJsonPathPattern>),
    EqualToXmlPattern(Box<models::EqualToXmlPattern>),
    MatchesXpathPattern(Box<models::MatchesXpathPattern>),
    MatchesJsonSchemaPattern(Box<models::MatchesJsonSchemaPattern>),
    AbsentPattern(Box<models::AbsentPattern>),
    AndPattern(Box<models::AndPattern>),
    OrPattern(Box<models::OrPattern>),
    HasExactlyMultivaluePattern(Box<models::HasExactlyMultivaluePattern>),
    IncludesMultivaluePattern(Box<models::IncludesMultivaluePattern>),
}

impl Default for ContentPattern {
    fn default() -> Self {
        Self::EqualToPattern(Default::default())
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum NamespaceAwareness {
    #[serde(rename = "LEGACY")]
    Legacy,
    #[serde(rename = "STRICT")]
    Strict,
    #[serde(rename = "NONE")]
    None,
}

impl Default for NamespaceAwareness {
    fn default() -> NamespaceAwareness {
        Self::Legacy
    }
}
/// The JSON schema version to interpret the schema against
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum SchemaVersion {
    #[serde(rename = "V4")]
    V4,
    #[serde(rename = "V6")]
    V6,
    #[serde(rename = "V7")]
    V7,
    #[serde(rename = "V201909")]
    V201909,
    #[serde(rename = "V202012")]
    V202012,
}

impl Default for SchemaVersion {
    fn default() -> SchemaVersion {
        Self::V4
    }
}

