/*
 * WireMock
 *
 * WireMock offers a REST API for administration, troubleshooting and analysis purposes
 *
 * The version of the OpenAPI document: 3.13.2
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum EqualToJsonPatternEqualToJson {
    /// The JSON object to match.
    Object(serde_json::Value),
    /// A JSON-encoded JSON string to match.
    String(String),
}

impl Default for EqualToJsonPatternEqualToJson {
    fn default() -> Self {
        Self::Object(Default::default())
    }
}

