/*
 * WireMock
 *
 * WireMock offers a REST API for administration, troubleshooting and analysis purposes
 *
 * The version of the OpenAPI document: 3.13.2
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct EqualToJsonPattern {
    #[serde(rename = "equalToJson")]
    pub equal_to_json: Box<models::EqualToJsonPatternEqualToJson>,
    #[serde(rename = "ignoreExtraElements", skip_serializing_if = "Option::is_none")]
    pub ignore_extra_elements: Option<bool>,
    #[serde(rename = "ignoreArrayOrder", skip_serializing_if = "Option::is_none")]
    pub ignore_array_order: Option<bool>,
}

impl EqualToJsonPattern {
    pub fn new(equal_to_json: models::EqualToJsonPatternEqualToJson) -> EqualToJsonPattern {
        EqualToJsonPattern {
            equal_to_json: Box::new(equal_to_json),
            ignore_extra_elements: None,
            ignore_array_order: None,
        }
    }
}

