/*
 * WireMock
 *
 * WireMock offers a REST API for administration, troubleshooting and analysis purposes
 *
 * The version of the OpenAPI document: 3.13.2
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct EqualToPattern {
    #[serde(rename = "equalTo")]
    pub equal_to: String,
    #[serde(rename = "caseInsensitive", skip_serializing_if = "Option::is_none")]
    pub case_insensitive: Option<bool>,
}

impl EqualToPattern {
    pub fn new(equal_to: String) -> EqualToPattern {
        EqualToPattern {
            equal_to,
            case_insensitive: None,
        }
    }
}

