/*
 * WireMock
 *
 * WireMock offers a REST API for administration, troubleshooting and analysis purposes
 *
 * The version of the OpenAPI document: 3.13.2
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// Fixed : Fixed response delay.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Fixed {
    #[serde(rename = "milliseconds")]
    pub milliseconds: i32,
    #[serde(rename = "type", skip_serializing_if = "Option::is_none")]
    pub r#type: Option<Type>,
}

impl Fixed {
    /// Fixed response delay.
    pub fn new(milliseconds: i32) -> Fixed {
        Fixed {
            milliseconds,
            r#type: None,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "fixed")]
    Fixed,
}

impl Default for Type {
    fn default() -> Type {
        Self::Fixed
    }
}

