/*
 * WireMock
 *
 * WireMock offers a REST API for administration, troubleshooting and analysis purposes
 *
 * The version of the OpenAPI document: 3.13.2
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetAllScenarios200Response {
    #[serde(rename = "scenarios", skip_serializing_if = "Option::is_none")]
    pub scenarios: Option<Vec<models::Scenario>>,
}

impl GetAllScenarios200Response {
    pub fn new() -> GetAllScenarios200Response {
        GetAllScenarios200Response {
            scenarios: None,
        }
    }
}

