/*
 * WireMock
 *
 * WireMock offers a REST API for administration, troubleshooting and analysis purposes
 *
 * The version of the OpenAPI document: 3.13.2
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetRecordingStatus200Response {
    #[serde(rename = "status", skip_serializing_if = "Option::is_none")]
    pub status: Option<Status>,
}

impl GetRecordingStatus200Response {
    pub fn new() -> GetRecordingStatus200Response {
        GetRecordingStatus200Response {
            status: None,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Status {
    #[serde(rename = "NeverStarted")]
    NeverStarted,
    #[serde(rename = "Recording")]
    Recording,
    #[serde(rename = "Stopped")]
    Stopped,
}

impl Default for Status {
    fn default() -> Status {
        Self::NeverStarted
    }
}

