/*
 * WireMock
 *
 * WireMock offers a REST API for administration, troubleshooting and analysis purposes
 *
 * The version of the OpenAPI document: 3.13.2
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct LoggedRequest {
    /// The unique identifier for this request
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<uuid::Uuid>,
    /// The HTTP request method
    #[serde(rename = "method", skip_serializing_if = "Option::is_none")]
    pub method: Option<String>,
    /// The path and query to match exactly against
    #[serde(rename = "url", skip_serializing_if = "Option::is_none")]
    pub url: Option<String>,
    /// The full URL to match against
    #[serde(rename = "absoluteUrl", skip_serializing_if = "Option::is_none")]
    pub absolute_url: Option<String>,
    /// The URL scheme (http/https)
    #[serde(rename = "scheme", skip_serializing_if = "Option::is_none")]
    pub scheme: Option<String>,
    /// The host part of the URL
    #[serde(rename = "host", skip_serializing_if = "Option::is_none")]
    pub host: Option<String>,
    /// The port number
    #[serde(rename = "port", skip_serializing_if = "Option::is_none")]
    pub port: Option<i32>,
    /// The client IP address
    #[serde(rename = "clientIp", skip_serializing_if = "Option::is_none")]
    pub client_ip: Option<String>,
    /// HTTP headers
    #[serde(rename = "headers", skip_serializing_if = "Option::is_none")]
    pub headers: Option<std::collections::HashMap<String, models::HeadersValue>>,
    /// Cookies received with the request
    #[serde(rename = "cookies", skip_serializing_if = "Option::is_none")]
    pub cookies: Option<std::collections::HashMap<String, models::LoggedRequestCookiesValue>>,
    /// Body string to match against
    #[serde(rename = "body", skip_serializing_if = "Option::is_none")]
    pub body: Option<String>,
    /// Base64 encoded body content
    #[serde(rename = "bodyAsBase64", skip_serializing_if = "Option::is_none")]
    pub body_as_base64: Option<String>,
    /// Whether this request was made via a browser proxy
    #[serde(rename = "browserProxyRequest", skip_serializing_if = "Option::is_none")]
    pub browser_proxy_request: Option<bool>,
    /// The timestamp when the request was logged (epoch millis)
    #[serde(rename = "loggedDate", skip_serializing_if = "Option::is_none")]
    pub logged_date: Option<i64>,
    /// The formatted date string when the request was logged
    #[serde(rename = "loggedDateString", skip_serializing_if = "Option::is_none")]
    pub logged_date_string: Option<String>,
    /// Query parameters parsed from the URL
    #[serde(rename = "queryParams", skip_serializing_if = "Option::is_none")]
    pub query_params: Option<std::collections::HashMap<String, models::HeadersValue>>,
    /// Form parameters parsed from the request body
    #[serde(rename = "formParams", skip_serializing_if = "Option::is_none")]
    pub form_params: Option<std::collections::HashMap<String, models::HeadersValue>>,
    /// Multipart form data parts
    #[serde(rename = "multiparts", skip_serializing_if = "Option::is_none")]
    pub multiparts: Option<Vec<models::LoggedRequestMultipartsInner>>,
    /// The HTTP protocol version
    #[serde(rename = "protocol", skip_serializing_if = "Option::is_none")]
    pub protocol: Option<String>,
}

impl LoggedRequest {
    pub fn new() -> LoggedRequest {
        LoggedRequest {
            id: None,
            method: None,
            url: None,
            absolute_url: None,
            scheme: None,
            host: None,
            port: None,
            client_ip: None,
            headers: None,
            cookies: None,
            body: None,
            body_as_base64: None,
            browser_proxy_request: None,
            logged_date: None,
            logged_date_string: None,
            query_params: None,
            form_params: None,
            multiparts: None,
            protocol: None,
        }
    }
}

