/*
 * WireMock
 *
 * WireMock offers a REST API for administration, troubleshooting and analysis purposes
 *
 * The version of the OpenAPI document: 3.13.2
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MatchesJsonPathPattern {
    #[serde(rename = "matchesJsonPath")]
    pub matches_json_path: Box<models::MatchesJsonPathPatternMatchesJsonPath>,
}

impl MatchesJsonPathPattern {
    pub fn new(matches_json_path: models::MatchesJsonPathPatternMatchesJsonPath) -> MatchesJsonPathPattern {
        MatchesJsonPathPattern {
            matches_json_path: Box::new(matches_json_path),
        }
    }
}

