/*
 * WireMock
 *
 * WireMock offers a REST API for administration, troubleshooting and analysis purposes
 *
 * The version of the OpenAPI document: 3.13.2
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum MatchesJsonPathPatternMatchesJsonPath {
    String(String),
    MatchesJsonPathPatternMatchesJsonPathOneOf(Box<models::MatchesJsonPathPatternMatchesJsonPathOneOf>),
}

impl Default for MatchesJsonPathPatternMatchesJsonPath {
    fn default() -> Self {
        Self::String(Default::default())
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum NamespaceAwareness {
    #[serde(rename = "LEGACY")]
    Legacy,
    #[serde(rename = "STRICT")]
    Strict,
    #[serde(rename = "NONE")]
    None,
}

impl Default for NamespaceAwareness {
    fn default() -> NamespaceAwareness {
        Self::Legacy
    }
}
/// The JSON schema version to interpret the schema against
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum SchemaVersion {
    #[serde(rename = "V4")]
    V4,
    #[serde(rename = "V6")]
    V6,
    #[serde(rename = "V7")]
    V7,
    #[serde(rename = "V201909")]
    V201909,
    #[serde(rename = "V202012")]
    V202012,
}

impl Default for SchemaVersion {
    fn default() -> SchemaVersion {
        Self::V4
    }
}

