/*
 * WireMock
 *
 * WireMock offers a REST API for administration, troubleshooting and analysis purposes
 *
 * The version of the OpenAPI document: 3.13.2
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MatchesXpathPattern {
    #[serde(rename = "matchesXPath")]
    pub matches_x_path: Box<models::MatchesXpathPatternMatchesXPath>,
    #[serde(rename = "xPathNamespaces", skip_serializing_if = "Option::is_none")]
    pub x_path_namespaces: Option<std::collections::HashMap<String, String>>,
}

impl MatchesXpathPattern {
    pub fn new(matches_x_path: models::MatchesXpathPatternMatchesXPath) -> MatchesXpathPattern {
        MatchesXpathPattern {
            matches_x_path: Box::new(matches_x_path),
            x_path_namespaces: None,
        }
    }
}

