/*
 * WireMock
 *
 * WireMock offers a REST API for administration, troubleshooting and analysis purposes
 *
 * The version of the OpenAPI document: 3.13.2
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MatchesJsonSchemaPattern {
    /// A valid JSON schema as a string
    #[serde(rename = "matchesJsonSchema")]
    pub matches_json_schema: String,
    /// The JSON schema version to interpret the schema against
    #[serde(rename = "schemaVersion", skip_serializing_if = "Option::is_none")]
    pub schema_version: Option<SchemaVersion>,
}

impl MatchesJsonSchemaPattern {
    pub fn new(matches_json_schema: String) -> MatchesJsonSchemaPattern {
        MatchesJsonSchemaPattern {
            matches_json_schema,
            schema_version: None,
        }
    }
}
/// The JSON schema version to interpret the schema against
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum SchemaVersion {
    #[serde(rename = "V4")]
    V4,
    #[serde(rename = "V6")]
    V6,
    #[serde(rename = "V7")]
    V7,
    #[serde(rename = "V201909")]
    V201909,
    #[serde(rename = "V202012")]
    V202012,
}

impl Default for SchemaVersion {
    fn default() -> SchemaVersion {
        Self::V4
    }
}

