/*
 * WireMock
 *
 * WireMock offers a REST API for administration, troubleshooting and analysis purposes
 *
 * The version of the OpenAPI document: 3.13.2
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// RecordSpecRequestBodyPattern : Control the request body matcher used in generated stub mappings
/// Control the request body matcher used in generated stub mappings
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum RecordSpecRequestBodyPattern {
    RecordSpecRequestBodyPatternOneOf(Box<models::RecordSpecRequestBodyPatternOneOf>),
    RecordSpecRequestBodyPatternOneOf1(Box<models::RecordSpecRequestBodyPatternOneOf1>),
    RecordSpecRequestBodyPatternOneOf2(Box<models::RecordSpecRequestBodyPatternOneOf2>),
    RecordSpecRequestBodyPatternOneOf3(Box<models::RecordSpecRequestBodyPatternOneOf3>),
}

impl Default for RecordSpecRequestBodyPattern {
    fn default() -> Self {
        Self::RecordSpecRequestBodyPatternOneOf(Default::default())
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Matcher {
    #[serde(rename = "equalToXml")]
    EqualToXml,
}

impl Default for Matcher {
    fn default() -> Matcher {
        Self::EqualToXml
    }
}

