/*
 * WireMock
 *
 * WireMock offers a REST API for administration, troubleshooting and analysis purposes
 *
 * The version of the OpenAPI document: 3.13.2
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// RecordSpecRequestBodyPatternOneOf : Automatically determine matcher based on content type (the default)
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RecordSpecRequestBodyPatternOneOf {
    /// If equalTo is used, match body use case-insensitive string comparison
    #[serde(rename = "caseInsensitive", skip_serializing_if = "Option::is_none")]
    pub case_insensitive: Option<bool>,
    /// If equalToJson is used, ignore order of array elements
    #[serde(rename = "ignoreArrayOrder", skip_serializing_if = "Option::is_none")]
    pub ignore_array_order: Option<bool>,
    /// If equalToJson is used, matcher ignores extra elements in objects
    #[serde(rename = "ignoreExtraElements", skip_serializing_if = "Option::is_none")]
    pub ignore_extra_elements: Option<bool>,
    #[serde(rename = "matcher", skip_serializing_if = "Option::is_none")]
    pub matcher: Option<Matcher>,
}

impl RecordSpecRequestBodyPatternOneOf {
    /// Automatically determine matcher based on content type (the default)
    pub fn new() -> RecordSpecRequestBodyPatternOneOf {
        RecordSpecRequestBodyPatternOneOf {
            case_insensitive: None,
            ignore_array_order: None,
            ignore_extra_elements: None,
            matcher: None,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Matcher {
    #[serde(rename = "auto")]
    Auto,
}

impl Default for Matcher {
    fn default() -> Matcher {
        Self::Auto
    }
}

