/*
 * WireMock
 *
 * WireMock offers a REST API for administration, troubleshooting and analysis purposes
 *
 * The version of the OpenAPI document: 3.13.2
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// RecordSpecExtractBodyCriteria : Criteria for extracting response bodies to a separate file instead of including it in the stub mapping
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RecordSpecExtractBodyCriteria {
    /// Size threshold for extracting binary response bodies. Supports humanized size strings, e.g. \"56 Mb\". Default unit is bytes.
    #[serde(rename = "binarySizeThreshold", skip_serializing_if = "Option::is_none")]
    pub binary_size_threshold: Option<String>,
    /// Size threshold for extracting binary response bodies. Supports humanized size strings, e.g. \"56 Mb\". Default unit is bytes.
    #[serde(rename = "textSizeThreshold", skip_serializing_if = "Option::is_none")]
    pub text_size_threshold: Option<String>,
}

impl RecordSpecExtractBodyCriteria {
    /// Criteria for extracting response bodies to a separate file instead of including it in the stub mapping
    pub fn new() -> RecordSpecExtractBodyCriteria {
        RecordSpecExtractBodyCriteria {
            binary_size_threshold: None,
            text_size_threshold: None,
        }
    }
}

