/*
 * WireMock
 *
 * WireMock offers a REST API for administration, troubleshooting and analysis purposes
 *
 * The version of the OpenAPI document: 3.13.2
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// RequestPatternCustomMatcher : Custom request matcher to match against
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RequestPatternCustomMatcher {
    /// The matcher's name specified in the implementation of the matcher.
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "parameters", skip_serializing_if = "Option::is_none")]
    pub parameters: Option<serde_json::Value>,
}

impl RequestPatternCustomMatcher {
    /// Custom request matcher to match against
    pub fn new() -> RequestPatternCustomMatcher {
        RequestPatternCustomMatcher {
            name: None,
            parameters: None,
        }
    }
}

