/*
 * WireMock
 *
 * WireMock offers a REST API for administration, troubleshooting and analysis purposes
 *
 * The version of the OpenAPI document: 3.13.2
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RequestPatternMultipartPatternsInner {
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "fileName", skip_serializing_if = "Option::is_none")]
    pub file_name: Option<String>,
    /// Determines whether all or any of the parts must match the criteria for an overall match.
    #[serde(rename = "matchingType", skip_serializing_if = "Option::is_none")]
    pub matching_type: Option<MatchingType>,
    /// Header patterns to match against in the <key>: { \"<predicate>\": \"<value>\" } form
    #[serde(rename = "headers", skip_serializing_if = "Option::is_none")]
    pub headers: Option<std::collections::HashMap<String, models::ContentPattern>>,
    /// Body patterns to match against in the { \"<predicate>\": \"<value>\" } form
    #[serde(rename = "bodyPatterns", skip_serializing_if = "Option::is_none")]
    pub body_patterns: Option<Vec<models::ContentPattern>>,
}

impl RequestPatternMultipartPatternsInner {
    pub fn new() -> RequestPatternMultipartPatternsInner {
        RequestPatternMultipartPatternsInner {
            name: None,
            file_name: None,
            matching_type: None,
            headers: None,
            body_patterns: None,
        }
    }
}
/// Determines whether all or any of the parts must match the criteria for an overall match.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum MatchingType {
    #[serde(rename = "ALL")]
    All,
    #[serde(rename = "ANY")]
    Any,
}

impl Default for MatchingType {
    fn default() -> MatchingType {
        Self::All
    }
}

