/*
 * WireMock
 *
 * WireMock offers a REST API for administration, troubleshooting and analysis purposes
 *
 * The version of the OpenAPI document: 3.13.2
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// RequestPatternBasicAuthCredentials : Pre-emptive basic auth credentials to match against
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RequestPatternBasicAuthCredentials {
    #[serde(rename = "password")]
    pub password: String,
    #[serde(rename = "username")]
    pub username: String,
}

impl RequestPatternBasicAuthCredentials {
    /// Pre-emptive basic auth credentials to match against
    pub fn new(password: String, username: String) -> RequestPatternBasicAuthCredentials {
        RequestPatternBasicAuthCredentials {
            password,
            username,
        }
    }
}

