/*
 * WireMock
 *
 * WireMock offers a REST API for administration, troubleshooting and analysis purposes
 *
 * The version of the OpenAPI document: 3.13.2
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RequestPattern {
    /// The scheme (protocol) part of the request URL
    #[serde(rename = "scheme", skip_serializing_if = "Option::is_none")]
    pub scheme: Option<Scheme>,
    /// The hostname part of the request URL
    #[serde(rename = "host", skip_serializing_if = "Option::is_none")]
    pub host: Option<String>,
    /// The HTTP port number of the request URL
    #[serde(rename = "port", skip_serializing_if = "Option::is_none")]
    pub port: Option<i32>,
    /// The HTTP request method e.g. GET
    #[serde(rename = "method", skip_serializing_if = "Option::is_none")]
    pub method: Option<String>,
    /// The path and query to match exactly against. Only one of url, urlPattern, urlPath or urlPathPattern may be specified.
    #[serde(rename = "url", skip_serializing_if = "Option::is_none")]
    pub url: Option<String>,
    /// The path to match exactly against. Only one of url, urlPattern, urlPath or urlPathPattern may be specified.
    #[serde(rename = "urlPath", skip_serializing_if = "Option::is_none")]
    pub url_path: Option<String>,
    /// The path regex to match against. Only one of url, urlPattern, urlPath or urlPathPattern may be specified.
    #[serde(rename = "urlPathPattern", skip_serializing_if = "Option::is_none")]
    pub url_path_pattern: Option<String>,
    /// The path and query regex to match against. Only one of url, urlPattern, urlPath or urlPathPattern may be specified.
    #[serde(rename = "urlPattern", skip_serializing_if = "Option::is_none")]
    pub url_pattern: Option<String>,
    /// The path template to match against. Must conform to the OpenAPI compatible subset of the RFC 6570 URI Template specification. Only one of url, urlPattern, urlPath or urlPathPattern may be specified. 
    #[serde(rename = "urlPathTemplate", skip_serializing_if = "Option::is_none")]
    pub url_path_template: Option<String>,
    /// Path parameter patterns to match against in the <key>: { \"<predicate>\": \"<value>\" } form. Can only be used when the urlPathPattern URL match type is in use and all keys must be present as variables in the path template.
    #[serde(rename = "pathParameters", skip_serializing_if = "Option::is_none")]
    pub path_parameters: Option<std::collections::HashMap<String, models::ContentPattern>>,
    /// Query parameter patterns to match against in the <key>: { \"<predicate>\": \"<value>\" } form
    #[serde(rename = "queryParameters", skip_serializing_if = "Option::is_none")]
    pub query_parameters: Option<std::collections::HashMap<String, models::ContentPattern>>,
    /// application/x-www-form-urlencoded form parameter patterns to match against in the <key>: { \"<predicate>\": \"<value>\" } form
    #[serde(rename = "formParameters", skip_serializing_if = "Option::is_none")]
    pub form_parameters: Option<std::collections::HashMap<String, models::ContentPattern>>,
    /// Header patterns to match against in the <key>: { \"<predicate>\": \"<value>\" } form
    #[serde(rename = "headers", skip_serializing_if = "Option::is_none")]
    pub headers: Option<std::collections::HashMap<String, models::ContentPattern>>,
    /// The client IP address to match against
    #[serde(rename = "clientIp", skip_serializing_if = "Option::is_none")]
    pub client_ip: Option<String>,
    #[serde(rename = "basicAuthCredentials", skip_serializing_if = "Option::is_none")]
    pub basic_auth_credentials: Option<Box<models::RequestPatternBasicAuthCredentials>>,
    /// Cookie patterns to match against in the <key>: { \"<predicate>\": \"<value>\" } form
    #[serde(rename = "cookies", skip_serializing_if = "Option::is_none")]
    pub cookies: Option<std::collections::HashMap<String, models::ContentPattern>>,
    /// Request body patterns to match against in the { \"<predicate>\": \"<value>\" } form
    #[serde(rename = "bodyPatterns", skip_serializing_if = "Option::is_none")]
    pub body_patterns: Option<Vec<models::ContentPattern>>,
    #[serde(rename = "customMatcher", skip_serializing_if = "Option::is_none")]
    pub custom_matcher: Option<Box<models::RequestPatternCustomMatcher>>,
    /// Multipart patterns to match against headers and body.
    #[serde(rename = "multipartPatterns", skip_serializing_if = "Option::is_none")]
    pub multipart_patterns: Option<Vec<models::RequestPatternMultipartPatternsInner>>,
}

impl RequestPattern {
    pub fn new() -> RequestPattern {
        RequestPattern {
            scheme: None,
            host: None,
            port: None,
            method: None,
            url: None,
            url_path: None,
            url_path_pattern: None,
            url_pattern: None,
            url_path_template: None,
            path_parameters: None,
            query_parameters: None,
            form_parameters: None,
            headers: None,
            client_ip: None,
            basic_auth_credentials: None,
            cookies: None,
            body_patterns: None,
            custom_matcher: None,
            multipart_patterns: None,
        }
    }
}
/// The scheme (protocol) part of the request URL
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Scheme {
    #[serde(rename = "http")]
    Http,
    #[serde(rename = "https")]
    Https,
}

impl Default for Scheme {
    fn default() -> Scheme {
        Self::Http
    }
}

