/*
 * WireMock
 *
 * WireMock offers a REST API for administration, troubleshooting and analysis purposes
 *
 * The version of the OpenAPI document: 3.13.2
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ResponseDefinition {
    /// The HTTP status code to be returned
    #[serde(rename = "status", skip_serializing_if = "Option::is_none")]
    pub status: Option<i32>,
    /// The HTTP status message to be returned
    #[serde(rename = "statusMessage", skip_serializing_if = "Option::is_none")]
    pub status_message: Option<String>,
    /// Map of response headers to send
    #[serde(rename = "headers", skip_serializing_if = "Option::is_none")]
    pub headers: Option<std::collections::HashMap<String, String>>,
    /// Extra request headers to send when proxying to another host.
    #[serde(rename = "additionalProxyRequestHeaders", skip_serializing_if = "Option::is_none")]
    pub additional_proxy_request_headers: Option<std::collections::HashMap<String, String>>,
    /// Request headers to remove when proxying to another host.
    #[serde(rename = "removeProxyRequestHeaders", skip_serializing_if = "Option::is_none")]
    pub remove_proxy_request_headers: Option<Vec<String>>,
    /// The response body as a string. Only one of body, base64Body, jsonBody or bodyFileName may be specified.
    #[serde(rename = "body", skip_serializing_if = "Option::is_none")]
    pub body: Option<String>,
    /// A base64 encoded string used to describe binary data.
    #[serde(rename = "base64Body", skip_serializing_if = "Option::is_none")]
    pub base64_body: Option<String>,
    #[serde(rename = "jsonBody", skip_serializing_if = "Option::is_none")]
    pub json_body: Option<Box<models::ResponseDefinitionAllOfJsonBody>>,
    /// The path to the file containing the response body, relative to the configured file root. Only one of body, base64Body, jsonBody or bodyFileName may be specified.
    #[serde(rename = "bodyFileName", skip_serializing_if = "Option::is_none")]
    pub body_file_name: Option<String>,
    /// The fault to apply (instead of a full, valid response).
    #[serde(rename = "fault", skip_serializing_if = "Option::is_none")]
    pub fault: Option<Fault>,
    /// Number of milliseconds to delay be before sending the response.
    #[serde(rename = "fixedDelayMilliseconds", skip_serializing_if = "Option::is_none")]
    pub fixed_delay_milliseconds: Option<i32>,
    #[serde(rename = "delayDistribution", skip_serializing_if = "Option::is_none")]
    pub delay_distribution: Option<Box<models::DelayDistribution>>,
    #[serde(rename = "chunkedDribbleDelay", skip_serializing_if = "Option::is_none")]
    pub chunked_dribble_delay: Option<Box<models::ResponseDefinitionAllOfChunkedDribbleDelay>>,
    /// Read-only flag indicating false if this was the default, unmatched response. Not present otherwise.
    #[serde(rename = "fromConfiguredStub", skip_serializing_if = "Option::is_none")]
    pub from_configured_stub: Option<bool>,
    /// The base URL of the target to proxy matching requests to.
    #[serde(rename = "proxyBaseUrl", skip_serializing_if = "Option::is_none")]
    pub proxy_base_url: Option<String>,
    /// A path segment to remove from the beginning in incoming request URL paths before proxying to the target.
    #[serde(rename = "proxyUrlPrefixToRemove", skip_serializing_if = "Option::is_none")]
    pub proxy_url_prefix_to_remove: Option<String>,
    /// Parameters to apply to response transformers.
    #[serde(rename = "transformerParameters", skip_serializing_if = "Option::is_none")]
    pub transformer_parameters: Option<serde_json::Value>,
    /// List of names of transformers to apply to this response.
    #[serde(rename = "transformers", skip_serializing_if = "Option::is_none")]
    pub transformers: Option<Vec<String>>,
}

impl ResponseDefinition {
    pub fn new() -> ResponseDefinition {
        ResponseDefinition {
            status: None,
            status_message: None,
            headers: None,
            additional_proxy_request_headers: None,
            remove_proxy_request_headers: None,
            body: None,
            base64_body: None,
            json_body: None,
            body_file_name: None,
            fault: None,
            fixed_delay_milliseconds: None,
            delay_distribution: None,
            chunked_dribble_delay: None,
            from_configured_stub: None,
            proxy_base_url: None,
            proxy_url_prefix_to_remove: None,
            transformer_parameters: None,
            transformers: None,
        }
    }
}
/// The fault to apply (instead of a full, valid response).
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Fault {
    #[serde(rename = "CONNECTION_RESET_BY_PEER")]
    ConnectionResetByPeer,
    #[serde(rename = "EMPTY_RESPONSE")]
    EmptyResponse,
    #[serde(rename = "MALFORMED_RESPONSE_CHUNK")]
    MalformedResponseChunk,
    #[serde(rename = "RANDOM_DATA_THEN_CLOSE")]
    RandomDataThenClose,
}

impl Default for Fault {
    fn default() -> Fault {
        Self::ConnectionResetByPeer
    }
}

