/*
 * WireMock
 *
 * WireMock offers a REST API for administration, troubleshooting and analysis purposes
 *
 * The version of the OpenAPI document: 3.13.2
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ResponseDefinitionAllOfJsonBody : The response body as a JSON object. Only one of body, base64Body, jsonBody or bodyFileName may be specified.
/// The response body as a JSON object. Only one of body, base64Body, jsonBody or bodyFileName may be specified.
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ResponseDefinitionAllOfJsonBody {
    Object(serde_json::Value),
    ArrayVecString(Vec<String>),
}

impl Default for ResponseDefinitionAllOfJsonBody {
    fn default() -> Self {
        Self::Object(Default::default())
    }
}

