/*
 * WireMock
 *
 * WireMock offers a REST API for administration, troubleshooting and analysis purposes
 *
 * The version of the OpenAPI document: 3.13.2
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct StubMapping {
    /// This stub mapping's unique identifier
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    /// Alias for the id
    #[serde(rename = "uuid", skip_serializing_if = "Option::is_none")]
    pub uuid: Option<String>,
    /// The stub mapping's name
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "request", skip_serializing_if = "Option::is_none")]
    pub request: Option<Box<models::RequestPattern>>,
    #[serde(rename = "response", skip_serializing_if = "Option::is_none")]
    pub response: Option<Box<models::ResponseDefinition>>,
    /// Indicates that the stub mapping should be persisted immediately on create/update/delete and survive resets to default.
    #[serde(rename = "persistent", skip_serializing_if = "Option::is_none")]
    pub persistent: Option<bool>,
    /// This stub mapping's priority relative to others. 1 is highest.
    #[serde(rename = "priority", skip_serializing_if = "Option::is_none")]
    pub priority: Option<i32>,
    /// The name of the scenario that this stub mapping is part of
    #[serde(rename = "scenarioName", skip_serializing_if = "Option::is_none")]
    pub scenario_name: Option<String>,
    /// The required state of the scenario in order for this stub to be matched.
    #[serde(rename = "requiredScenarioState", skip_serializing_if = "Option::is_none")]
    pub required_scenario_state: Option<String>,
    /// The new state for the scenario to be updated to after this stub is served.
    #[serde(rename = "newScenarioState", skip_serializing_if = "Option::is_none")]
    pub new_scenario_state: Option<String>,
    /// DEPRECATED: Use `serveEventListeners` instead. A map of the names of post serve action extensions to trigger and their parameters. 
    #[serde(rename = "postServeActions", skip_serializing_if = "Option::is_none")]
    pub post_serve_actions: Option<Vec<serde_json::Value>>,
    /// The list of serve event listeners
    #[serde(rename = "serveEventListeners", skip_serializing_if = "Option::is_none")]
    pub serve_event_listeners: Option<Vec<models::StubMappingServeEventListenersInner>>,
    /// Arbitrary metadata to be used for e.g. tagging, documentation. Can also be used to find and remove stubs.
    #[serde(rename = "metadata", skip_serializing_if = "Option::is_none")]
    pub metadata: Option<serde_json::Value>,
}

impl StubMapping {
    pub fn new() -> StubMapping {
        StubMapping {
            id: None,
            uuid: None,
            name: None,
            request: None,
            response: None,
            persistent: None,
            priority: None,
            scenario_name: None,
            required_scenario_state: None,
            new_scenario_state: None,
            post_serve_actions: None,
            serve_event_listeners: None,
            metadata: None,
        }
    }
}

