/*
 * WireMock
 *
 * WireMock offers a REST API for administration, troubleshooting and analysis purposes
 *
 * The version of the OpenAPI document: 3.13.2
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TakeRecordingSnapshotRequest {
    /// Headers from the request to include in the generated stub mappings, mapped to parameter objects. The only parameter available is \"caseInsensitive\", which defaults to false
    #[serde(rename = "captureHeaders", skip_serializing_if = "Option::is_none")]
    pub capture_headers: Option<std::collections::HashMap<String, models::RecordSpecCaptureHeadersValue>>,
    #[serde(rename = "extractBodyCriteria", skip_serializing_if = "Option::is_none")]
    pub extract_body_criteria: Option<Box<models::RecordSpecExtractBodyCriteria>>,
    /// Whether to save stub mappings to the file system or just return them
    #[serde(rename = "persist", skip_serializing_if = "Option::is_none")]
    pub persist: Option<bool>,
    /// When true, duplicate requests will be added to a Scenario. When false, duplicates are discarded
    #[serde(rename = "repeatsAsScenarios", skip_serializing_if = "Option::is_none")]
    pub repeats_as_scenarios: Option<bool>,
    #[serde(rename = "requestBodyPattern", skip_serializing_if = "Option::is_none")]
    pub request_body_pattern: Option<Box<models::RecordSpecRequestBodyPattern>>,
    /// List of names of stub mappings transformers to apply to generated stubs
    #[serde(rename = "transformerParameters", skip_serializing_if = "Option::is_none")]
    pub transformer_parameters: Option<serde_json::Value>,
    /// Parameters to pass to stub mapping transformers
    #[serde(rename = "transformers", skip_serializing_if = "Option::is_none")]
    pub transformers: Option<Vec<String>>,
    #[serde(rename = "filters", skip_serializing_if = "Option::is_none")]
    pub filters: Option<Box<models::TakeRecordingSnapshotRequestAllOfFilters>>,
}

impl TakeRecordingSnapshotRequest {
    pub fn new() -> TakeRecordingSnapshotRequest {
        TakeRecordingSnapshotRequest {
            capture_headers: None,
            extract_body_criteria: None,
            persist: None,
            repeats_as_scenarios: None,
            request_body_pattern: None,
            transformer_parameters: None,
            transformers: None,
            filters: None,
        }
    }
}

