/*
 * WireMock
 *
 * WireMock offers a REST API for administration, troubleshooting and analysis purposes
 *
 * The version of the OpenAPI document: 3.13.2
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Truncation {
    #[serde(rename = "first second of minute")]
    FirstSecondOfMinute,
    #[serde(rename = "first minute of hour")]
    FirstMinuteOfHour,
    #[serde(rename = "first hour of day")]
    FirstHourOfDay,
    #[serde(rename = "first day of month")]
    FirstDayOfMonth,
    #[serde(rename = "first day of next month")]
    FirstDayOfNextMonth,
    #[serde(rename = "last day of month")]
    LastDayOfMonth,
    #[serde(rename = "first day of year")]
    FirstDayOfYear,
    #[serde(rename = "first day of next year")]
    FirstDayOfNextYear,
    #[serde(rename = "last day of year")]
    LastDayOfYear,

}

impl std::fmt::Display for Truncation {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::FirstSecondOfMinute => write!(f, "first second of minute"),
            Self::FirstMinuteOfHour => write!(f, "first minute of hour"),
            Self::FirstHourOfDay => write!(f, "first hour of day"),
            Self::FirstDayOfMonth => write!(f, "first day of month"),
            Self::FirstDayOfNextMonth => write!(f, "first day of next month"),
            Self::LastDayOfMonth => write!(f, "last day of month"),
            Self::FirstDayOfYear => write!(f, "first day of year"),
            Self::FirstDayOfNextYear => write!(f, "first day of next year"),
            Self::LastDayOfYear => write!(f, "last day of year"),
        }
    }
}

impl Default for Truncation {
    fn default() -> Truncation {
        Self::FirstSecondOfMinute
    }
}

