/*
 * WireMock
 *
 * WireMock offers a REST API for administration, troubleshooting and analysis purposes
 *
 * The version of the OpenAPI document: 3.13.2
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// Uniform : Uniformly distributed random response delay.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Uniform {
    #[serde(rename = "lower")]
    pub lower: i32,
    #[serde(rename = "upper")]
    pub upper: i32,
    #[serde(rename = "type", skip_serializing_if = "Option::is_none")]
    pub r#type: Option<Type>,
}

impl Uniform {
    /// Uniformly distributed random response delay.
    pub fn new(lower: i32, upper: i32) -> Uniform {
        Uniform {
            lower,
            upper,
            r#type: None,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "uniform")]
    Uniform,
}

impl Default for Type {
    fn default() -> Type {
        Self::Uniform
    }
}

