/*
 * WireMock
 *
 * WireMock offers a REST API for administration, troubleshooting and analysis purposes
 *
 * The version of the OpenAPI document: 3.13.2
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AbsentPattern {
    #[serde(rename = "absent")]
    pub absent: bool,
}

impl AbsentPattern {
    pub fn new(absent: bool) -> AbsentPattern {
        AbsentPattern {
            absent,
        }
    }
}

