/*
 * WireMock
 *
 * WireMock offers a REST API for administration, troubleshooting and analysis purposes
 *
 * The version of the OpenAPI document: 3.13.2
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AndPattern {
    #[serde(rename = "and")]
    pub and: Vec<models::ContentPattern>,
}

impl AndPattern {
    pub fn new(and: Vec<models::ContentPattern>) -> AndPattern {
        AndPattern {
            and,
        }
    }
}

