/*
 * WireMock
 *
 * WireMock offers a REST API for administration, troubleshooting and analysis purposes
 *
 * The version of the OpenAPI document: 3.13.2
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BeforePattern {
    #[serde(rename = "before")]
    pub before: String,
    #[serde(rename = "actualFormat", skip_serializing_if = "Option::is_none")]
    pub actual_format: Option<String>,
    #[serde(rename = "truncateExpected", skip_serializing_if = "Option::is_none")]
    pub truncate_expected: Option<models::Truncation>,
    #[serde(rename = "truncateActual", skip_serializing_if = "Option::is_none")]
    pub truncate_actual: Option<models::Truncation>,
}

impl BeforePattern {
    pub fn new(before: String) -> BeforePattern {
        BeforePattern {
            before,
            actual_format: None,
            truncate_expected: None,
            truncate_actual: None,
        }
    }
}

