/*
 * WireMock
 *
 * WireMock offers a REST API for administration, troubleshooting and analysis purposes
 *
 * The version of the OpenAPI document: 3.13.2
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BinaryEqualToPattern {
    /// A base64 encoded string used to describe binary data.
    #[serde(rename = "binaryEqualTo")]
    pub binary_equal_to: String,
}

impl BinaryEqualToPattern {
    pub fn new(binary_equal_to: String) -> BinaryEqualToPattern {
        BinaryEqualToPattern {
            binary_equal_to,
        }
    }
}

