/*
 * WireMock
 *
 * WireMock offers a REST API for administration, troubleshooting and analysis purposes
 *
 * The version of the OpenAPI document: 3.13.2
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ContainsPattern {
    #[serde(rename = "contains")]
    pub contains: String,
}

impl ContainsPattern {
    pub fn new(contains: String) -> ContainsPattern {
        ContainsPattern {
            contains,
        }
    }
}

