/*
 * WireMock
 *
 * WireMock offers a REST API for administration, troubleshooting and analysis purposes
 *
 * The version of the OpenAPI document: 3.13.2
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// DelayDistribution : The delay distribution. Valid property configuration is either median/sigma/type or lower/type/upper.
/// The delay distribution. Valid property configuration is either median/sigma/type or lower/type/upper.
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum DelayDistribution {
    LogNormal(Box<models::LogNormal>),
    Uniform(Box<models::Uniform>),
    Fixed(Box<models::Fixed>),
}

impl Default for DelayDistribution {
    fn default() -> Self {
        Self::LogNormal(Default::default())
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "lognormal")]
    Lognormal,
    #[serde(rename = "uniform")]
    Uniform,
    #[serde(rename = "fixed")]
    Fixed,
}

impl Default for Type {
    fn default() -> Type {
        Self::Lognormal
    }
}

