/*
 * WireMock
 *
 * WireMock offers a REST API for administration, troubleshooting and analysis purposes
 *
 * The version of the OpenAPI document: 3.13.2
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DoesNotMatchPattern {
    #[serde(rename = "doesNotMatch")]
    pub does_not_match: String,
}

impl DoesNotMatchPattern {
    pub fn new(does_not_match: String) -> DoesNotMatchPattern {
        DoesNotMatchPattern {
            does_not_match,
        }
    }
}

