/*
 * WireMock
 *
 * WireMock offers a REST API for administration, troubleshooting and analysis purposes
 *
 * The version of the OpenAPI document: 3.13.2
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DoesNotContainPattern {
    #[serde(rename = "doesNotContain")]
    pub does_not_contain: String,
}

impl DoesNotContainPattern {
    pub fn new(does_not_contain: String) -> DoesNotContainPattern {
        DoesNotContainPattern {
            does_not_contain,
        }
    }
}

