/*
 * WireMock
 *
 * WireMock offers a REST API for administration, troubleshooting and analysis purposes
 *
 * The version of the OpenAPI document: 3.13.2
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct EqualToXmlPattern {
    #[serde(rename = "equalToXml")]
    pub equal_to_xml: String,
    #[serde(rename = "enablePlaceholders", skip_serializing_if = "Option::is_none")]
    pub enable_placeholders: Option<bool>,
    #[serde(rename = "placeholderOpeningDelimiterRegex", skip_serializing_if = "Option::is_none")]
    pub placeholder_opening_delimiter_regex: Option<String>,
    #[serde(rename = "placeholderClosingDelimiterRegex", skip_serializing_if = "Option::is_none")]
    pub placeholder_closing_delimiter_regex: Option<String>,
    #[serde(rename = "namespaceAwareness", skip_serializing_if = "Option::is_none")]
    pub namespace_awareness: Option<NamespaceAwareness>,
}

impl EqualToXmlPattern {
    pub fn new(equal_to_xml: String) -> EqualToXmlPattern {
        EqualToXmlPattern {
            equal_to_xml,
            enable_placeholders: None,
            placeholder_opening_delimiter_regex: None,
            placeholder_closing_delimiter_regex: None,
            namespace_awareness: None,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum NamespaceAwareness {
    #[serde(rename = "LEGACY")]
    Legacy,
    #[serde(rename = "STRICT")]
    Strict,
    #[serde(rename = "NONE")]
    None,
}

impl Default for NamespaceAwareness {
    fn default() -> NamespaceAwareness {
        Self::Legacy
    }
}

