/*
 * WireMock
 *
 * WireMock offers a REST API for administration, troubleshooting and analysis purposes
 *
 * The version of the OpenAPI document: 3.13.2
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct HasExactlyMultivaluePattern {
    #[serde(rename = "hasExactly")]
    pub has_exactly: Vec<models::ContentPattern>,
}

impl HasExactlyMultivaluePattern {
    pub fn new(has_exactly: Vec<models::ContentPattern>) -> HasExactlyMultivaluePattern {
        HasExactlyMultivaluePattern {
            has_exactly,
        }
    }
}

