/*
 * WireMock
 *
 * WireMock offers a REST API for administration, troubleshooting and analysis purposes
 *
 * The version of the OpenAPI document: 3.13.2
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Health {
    /// The status of the server
    #[serde(rename = "status", skip_serializing_if = "Option::is_none")]
    pub status: Option<Status>,
    /// Longer message regarding the status of the server
    #[serde(rename = "message", skip_serializing_if = "Option::is_none")]
    pub message: Option<String>,
    /// The WireMock version
    #[serde(rename = "version", skip_serializing_if = "Option::is_none")]
    pub version: Option<String>,
    /// How long the server has been running
    #[serde(rename = "uptimeInSeconds", skip_serializing_if = "Option::is_none")]
    pub uptime_in_seconds: Option<i32>,
    /// The current timestamp
    #[serde(rename = "timestamp", skip_serializing_if = "Option::is_none")]
    pub timestamp: Option<String>,
}

impl Health {
    pub fn new() -> Health {
        Health {
            status: None,
            message: None,
            version: None,
            uptime_in_seconds: None,
            timestamp: None,
        }
    }
}
/// The status of the server
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Status {
    #[serde(rename = "healthy")]
    Healthy,
    #[serde(rename = "unhealthy")]
    Unhealthy,
}

impl Default for Status {
    fn default() -> Status {
        Self::Healthy
    }
}

