/*
 * WireMock
 *
 * WireMock offers a REST API for administration, troubleshooting and analysis purposes
 *
 * The version of the OpenAPI document: 3.13.2
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct IncludesMultivaluePattern {
    #[serde(rename = "includes")]
    pub includes: Vec<models::ContentPattern>,
}

impl IncludesMultivaluePattern {
    pub fn new(includes: Vec<models::ContentPattern>) -> IncludesMultivaluePattern {
        IncludesMultivaluePattern {
            includes,
        }
    }
}

