/*
 * WireMock
 *
 * WireMock offers a REST API for administration, troubleshooting and analysis purposes
 *
 * The version of the OpenAPI document: 3.13.2
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// LogNormal : Log normal randomly distributed response delay.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct LogNormal {
    #[serde(rename = "median")]
    pub median: i32,
    #[serde(rename = "sigma")]
    pub sigma: f64,
    #[serde(rename = "maxValue", skip_serializing_if = "Option::is_none")]
    pub max_value: Option<f64>,
    #[serde(rename = "type", skip_serializing_if = "Option::is_none")]
    pub r#type: Option<Type>,
}

impl LogNormal {
    /// Log normal randomly distributed response delay.
    pub fn new(median: i32, sigma: f64) -> LogNormal {
        LogNormal {
            median,
            sigma,
            max_value: None,
            r#type: None,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "lognormal")]
    Lognormal,
}

impl Default for Type {
    fn default() -> Type {
        Self::Lognormal
    }
}

