/*
 * WireMock
 *
 * WireMock offers a REST API for administration, troubleshooting and analysis purposes
 *
 * The version of the OpenAPI document: 3.13.2
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct LoggedRequestMultipartsInner {
    /// The name of the multipart part
    #[serde(rename = "name")]
    pub name: String,
    /// The filename of the multipart part, if provided
    #[serde(rename = "fileName", skip_serializing_if = "Option::is_none")]
    pub file_name: Option<String>,
    /// HTTP headers
    #[serde(rename = "headers", skip_serializing_if = "Option::is_none")]
    pub headers: Option<std::collections::HashMap<String, models::HeadersValue>>,
    /// The body content of this part
    #[serde(rename = "body", skip_serializing_if = "Option::is_none")]
    pub body: Option<String>,
    /// Base64 encoded body content of this part
    #[serde(rename = "bodyAsBase64", skip_serializing_if = "Option::is_none")]
    pub body_as_base64: Option<String>,
}

impl LoggedRequestMultipartsInner {
    pub fn new(name: String) -> LoggedRequestMultipartsInner {
        LoggedRequestMultipartsInner {
            name,
            file_name: None,
            headers: None,
            body: None,
            body_as_base64: None,
        }
    }
}

