/*
 * WireMock
 *
 * WireMock offers a REST API for administration, troubleshooting and analysis purposes
 *
 * The version of the OpenAPI document: 3.13.2
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MatchesXpathPatternMatchesXPathOneOf {
    #[serde(rename = "equalTo")]
    pub equal_to: String,
    #[serde(rename = "caseInsensitive", skip_serializing_if = "Option::is_none")]
    pub case_insensitive: Option<bool>,
    /// A base64 encoded string used to describe binary data.
    #[serde(rename = "binaryEqualTo")]
    pub binary_equal_to: String,
    #[serde(rename = "contains")]
    pub contains: String,
    #[serde(rename = "doesNotContain")]
    pub does_not_contain: String,
    #[serde(rename = "matches")]
    pub matches: String,
    #[serde(rename = "doesNotMatch")]
    pub does_not_match: String,
    #[serde(rename = "not")]
    pub not: Box<models::ContentPattern>,
    #[serde(rename = "before")]
    pub before: String,
    #[serde(rename = "actualFormat", skip_serializing_if = "Option::is_none")]
    pub actual_format: Option<String>,
    #[serde(rename = "truncateExpected", skip_serializing_if = "Option::is_none")]
    pub truncate_expected: Option<models::Truncation>,
    #[serde(rename = "truncateActual", skip_serializing_if = "Option::is_none")]
    pub truncate_actual: Option<models::Truncation>,
    #[serde(rename = "after")]
    pub after: String,
    #[serde(rename = "equalToDateTime")]
    pub equal_to_date_time: String,
    #[serde(rename = "equalToJson")]
    pub equal_to_json: Box<models::EqualToJsonPatternEqualToJson>,
    #[serde(rename = "ignoreExtraElements", skip_serializing_if = "Option::is_none")]
    pub ignore_extra_elements: Option<bool>,
    #[serde(rename = "ignoreArrayOrder", skip_serializing_if = "Option::is_none")]
    pub ignore_array_order: Option<bool>,
    #[serde(rename = "matchesJsonPath")]
    pub matches_json_path: Box<models::MatchesJsonPathPatternMatchesJsonPath>,
    #[serde(rename = "equalToXml")]
    pub equal_to_xml: String,
    #[serde(rename = "enablePlaceholders", skip_serializing_if = "Option::is_none")]
    pub enable_placeholders: Option<bool>,
    #[serde(rename = "placeholderOpeningDelimiterRegex", skip_serializing_if = "Option::is_none")]
    pub placeholder_opening_delimiter_regex: Option<String>,
    #[serde(rename = "placeholderClosingDelimiterRegex", skip_serializing_if = "Option::is_none")]
    pub placeholder_closing_delimiter_regex: Option<String>,
    #[serde(rename = "namespaceAwareness", skip_serializing_if = "Option::is_none")]
    pub namespace_awareness: Option<NamespaceAwareness>,
    #[serde(rename = "matchesXPath")]
    pub matches_x_path: Box<models::MatchesXpathPatternMatchesXPath>,
    #[serde(rename = "xPathNamespaces", skip_serializing_if = "Option::is_none")]
    pub x_path_namespaces: Option<std::collections::HashMap<String, String>>,
    /// A valid JSON schema as a string
    #[serde(rename = "matchesJsonSchema")]
    pub matches_json_schema: String,
    /// The JSON schema version to interpret the schema against
    #[serde(rename = "schemaVersion", skip_serializing_if = "Option::is_none")]
    pub schema_version: Option<SchemaVersion>,
    #[serde(rename = "absent")]
    pub absent: bool,
    #[serde(rename = "and")]
    pub and: Vec<models::ContentPattern>,
    #[serde(rename = "or")]
    pub or: Vec<models::ContentPattern>,
    #[serde(rename = "hasExactly")]
    pub has_exactly: Vec<models::ContentPattern>,
    #[serde(rename = "includes")]
    pub includes: Vec<models::ContentPattern>,
    #[serde(rename = "expression")]
    pub expression: String,
}

impl MatchesXpathPatternMatchesXPathOneOf {
    pub fn new(equal_to: String, binary_equal_to: String, contains: String, does_not_contain: String, matches: String, does_not_match: String, not: models::ContentPattern, before: String, after: String, equal_to_date_time: String, equal_to_json: models::EqualToJsonPatternEqualToJson, matches_json_path: models::MatchesJsonPathPatternMatchesJsonPath, equal_to_xml: String, matches_x_path: models::MatchesXpathPatternMatchesXPath, matches_json_schema: String, absent: bool, and: Vec<models::ContentPattern>, or: Vec<models::ContentPattern>, has_exactly: Vec<models::ContentPattern>, includes: Vec<models::ContentPattern>, expression: String) -> MatchesXpathPatternMatchesXPathOneOf {
        MatchesXpathPatternMatchesXPathOneOf {
            equal_to,
            case_insensitive: None,
            binary_equal_to,
            contains,
            does_not_contain,
            matches,
            does_not_match,
            not: Box::new(not),
            before,
            actual_format: None,
            truncate_expected: None,
            truncate_actual: None,
            after,
            equal_to_date_time,
            equal_to_json: Box::new(equal_to_json),
            ignore_extra_elements: None,
            ignore_array_order: None,
            matches_json_path: Box::new(matches_json_path),
            equal_to_xml,
            enable_placeholders: None,
            placeholder_opening_delimiter_regex: None,
            placeholder_closing_delimiter_regex: None,
            namespace_awareness: None,
            matches_x_path: Box::new(matches_x_path),
            x_path_namespaces: None,
            matches_json_schema,
            schema_version: None,
            absent,
            and,
            or,
            has_exactly,
            includes,
            expression,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum NamespaceAwareness {
    #[serde(rename = "LEGACY")]
    Legacy,
    #[serde(rename = "STRICT")]
    Strict,
    #[serde(rename = "NONE")]
    None,
}

impl Default for NamespaceAwareness {
    fn default() -> NamespaceAwareness {
        Self::Legacy
    }
}
/// The JSON schema version to interpret the schema against
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum SchemaVersion {
    #[serde(rename = "V4")]
    V4,
    #[serde(rename = "V6")]
    V6,
    #[serde(rename = "V7")]
    V7,
    #[serde(rename = "V201909")]
    V201909,
    #[serde(rename = "V202012")]
    V202012,
}

impl Default for SchemaVersion {
    fn default() -> SchemaVersion {
        Self::V4
    }
}

