/*
 * WireMock
 *
 * WireMock offers a REST API for administration, troubleshooting and analysis purposes
 *
 * The version of the OpenAPI document: 3.13.2
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct NotPattern {
    #[serde(rename = "not")]
    pub not: Box<models::ContentPattern>,
}

impl NotPattern {
    pub fn new(not: models::ContentPattern) -> NotPattern {
        NotPattern {
            not: Box::new(not),
        }
    }
}

