/*
 * WireMock
 *
 * WireMock offers a REST API for administration, troubleshooting and analysis purposes
 *
 * The version of the OpenAPI document: 3.13.2
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// RecordSpecRequestBodyPatternOneOf2 : Always match request bodies using equalToJson
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RecordSpecRequestBodyPatternOneOf2 {
    /// Ignore order of array elements
    #[serde(rename = "ignoreArrayOrder", skip_serializing_if = "Option::is_none")]
    pub ignore_array_order: Option<bool>,
    /// Ignore extra elements in objects
    #[serde(rename = "ignoreExtraElements", skip_serializing_if = "Option::is_none")]
    pub ignore_extra_elements: Option<bool>,
    #[serde(rename = "matcher", skip_serializing_if = "Option::is_none")]
    pub matcher: Option<Matcher>,
}

impl RecordSpecRequestBodyPatternOneOf2 {
    /// Always match request bodies using equalToJson
    pub fn new() -> RecordSpecRequestBodyPatternOneOf2 {
        RecordSpecRequestBodyPatternOneOf2 {
            ignore_array_order: None,
            ignore_extra_elements: None,
            matcher: None,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Matcher {
    #[serde(rename = "equalToJson")]
    EqualToJson,
}

impl Default for Matcher {
    fn default() -> Matcher {
        Self::EqualToJson
    }
}

