/*
 * WireMock
 *
 * WireMock offers a REST API for administration, troubleshooting and analysis purposes
 *
 * The version of the OpenAPI document: 3.13.2
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RecordSpecCaptureHeadersValue {
    #[serde(rename = "caseInsensitive", skip_serializing_if = "Option::is_none")]
    pub case_insensitive: Option<bool>,
}

impl RecordSpecCaptureHeadersValue {
    pub fn new() -> RecordSpecCaptureHeadersValue {
        RecordSpecCaptureHeadersValue {
            case_insensitive: None,
        }
    }
}

