/*
 * WireMock
 *
 * WireMock offers a REST API for administration, troubleshooting and analysis purposes
 *
 * The version of the OpenAPI document: 3.13.2
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// RecordSpecRequestBodyPatternOneOf3 : Always match request bodies using equalToXml
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RecordSpecRequestBodyPatternOneOf3 {
    #[serde(rename = "matcher", skip_serializing_if = "Option::is_none")]
    pub matcher: Option<Matcher>,
}

impl RecordSpecRequestBodyPatternOneOf3 {
    /// Always match request bodies using equalToXml
    pub fn new() -> RecordSpecRequestBodyPatternOneOf3 {
        RecordSpecRequestBodyPatternOneOf3 {
            matcher: None,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Matcher {
    #[serde(rename = "equalToXml")]
    EqualToXml,
}

impl Default for Matcher {
    fn default() -> Matcher {
        Self::EqualToXml
    }
}

