/*
 * WireMock
 *
 * WireMock offers a REST API for administration, troubleshooting and analysis purposes
 *
 * The version of the OpenAPI document: 3.13.2
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// RecordSpecRequestBodyPatternOneOf1 : Always match request bodies using equalTo
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RecordSpecRequestBodyPatternOneOf1 {
    /// Match body using case-insensitive string comparison
    #[serde(rename = "caseInsensitive", skip_serializing_if = "Option::is_none")]
    pub case_insensitive: Option<bool>,
    #[serde(rename = "matcher", skip_serializing_if = "Option::is_none")]
    pub matcher: Option<Matcher>,
}

impl RecordSpecRequestBodyPatternOneOf1 {
    /// Always match request bodies using equalTo
    pub fn new() -> RecordSpecRequestBodyPatternOneOf1 {
        RecordSpecRequestBodyPatternOneOf1 {
            case_insensitive: None,
            matcher: None,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Matcher {
    #[serde(rename = "equalTo")]
    EqualTo,
}

impl Default for Matcher {
    fn default() -> Matcher {
        Self::EqualTo
    }
}

