/*
 * WireMock
 *
 * WireMock offers a REST API for administration, troubleshooting and analysis purposes
 *
 * The version of the OpenAPI document: 3.13.2
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ResponseDefinitionAllOfChunkedDribbleDelay : The parameters for chunked dribble delay - chopping the response into pieces and sending them at delayed intervals
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ResponseDefinitionAllOfChunkedDribbleDelay {
    #[serde(rename = "numberOfChunks")]
    pub number_of_chunks: i32,
    #[serde(rename = "totalDuration")]
    pub total_duration: i32,
}

impl ResponseDefinitionAllOfChunkedDribbleDelay {
    /// The parameters for chunked dribble delay - chopping the response into pieces and sending them at delayed intervals
    pub fn new(number_of_chunks: i32, total_duration: i32) -> ResponseDefinitionAllOfChunkedDribbleDelay {
        ResponseDefinitionAllOfChunkedDribbleDelay {
            number_of_chunks,
            total_duration,
        }
    }
}

