/*
 * WireMock
 *
 * WireMock offers a REST API for administration, troubleshooting and analysis purposes
 *
 * The version of the OpenAPI document: 3.13.2
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RetrieveNearMissesForUnmatchedRequests200Response {
    #[serde(rename = "nearMisses", skip_serializing_if = "Option::is_none")]
    pub near_misses: Option<Vec<models::LoggedRequest>>,
}

impl RetrieveNearMissesForUnmatchedRequests200Response {
    pub fn new() -> RetrieveNearMissesForUnmatchedRequests200Response {
        RetrieveNearMissesForUnmatchedRequests200Response {
            near_misses: None,
        }
    }
}

