/*
 * WireMock
 *
 * WireMock offers a REST API for administration, troubleshooting and analysis purposes
 *
 * The version of the OpenAPI document: 3.13.2
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct StubMappingServeEventListenersInner {
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "requestPhases", skip_serializing_if = "Option::is_none")]
    pub request_phases: Option<Vec<RequestPhases>>,
    #[serde(rename = "parameters", skip_serializing_if = "Option::is_none")]
    pub parameters: Option<serde_json::Value>,
}

impl StubMappingServeEventListenersInner {
    pub fn new() -> StubMappingServeEventListenersInner {
        StubMappingServeEventListenersInner {
            name: None,
            request_phases: None,
            parameters: None,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum RequestPhases {
    #[serde(rename = "BEFORE_MATCH")]
    BeforeMatch,
    #[serde(rename = "AFTER_MATCH")]
    AfterMatch,
    #[serde(rename = "BEFORE_RESPONSE_SENT")]
    BeforeResponseSent,
    #[serde(rename = "AFTER_COMPLETE")]
    AfterComplete,
}

impl Default for RequestPhases {
    fn default() -> RequestPhases {
        Self::BeforeMatch
    }
}

