/*
 * WireMock
 *
 * WireMock offers a REST API for administration, troubleshooting and analysis purposes
 *
 * The version of the OpenAPI document: 3.13.2
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct StubMappingsMeta {
    #[serde(rename = "total")]
    pub total: i32,
}

impl StubMappingsMeta {
    pub fn new(total: i32) -> StubMappingsMeta {
        StubMappingsMeta {
            total,
        }
    }
}

