/*
 * WireMock
 *
 * WireMock offers a REST API for administration, troubleshooting and analysis purposes
 *
 * The version of the OpenAPI document: 3.13.2
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UpdateGlobalSettingsRequest {
    #[serde(rename = "median")]
    pub median: i32,
    #[serde(rename = "sigma")]
    pub sigma: f64,
    #[serde(rename = "maxValue", skip_serializing_if = "Option::is_none")]
    pub max_value: Option<f64>,
    #[serde(rename = "type", skip_serializing_if = "Option::is_none")]
    pub r#type: Option<Type>,
    #[serde(rename = "lower")]
    pub lower: i32,
    #[serde(rename = "upper")]
    pub upper: i32,
    #[serde(rename = "milliseconds")]
    pub milliseconds: i32,
    #[serde(rename = "fixedDelay", skip_serializing_if = "Option::is_none")]
    pub fixed_delay: Option<f64>,
}

impl UpdateGlobalSettingsRequest {
    pub fn new(median: i32, sigma: f64, lower: i32, upper: i32, milliseconds: i32) -> UpdateGlobalSettingsRequest {
        UpdateGlobalSettingsRequest {
            median,
            sigma,
            max_value: None,
            r#type: None,
            lower,
            upper,
            milliseconds,
            fixed_delay: None,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "fixed")]
    Fixed,
}

impl Default for Type {
    fn default() -> Type {
        Self::Fixed
    }
}

